import { HotkeyBinding } from '../types';

export function getDefaultBindings(): HotkeyBinding[] {
  return [
    // Global Application Shortcuts
    {
      id: 'toggle-sidebar',
      name: 'Toggle Sidebar',
      description: 'Show or hide the notes sidebar',
      scope: 'global',
      category: 'application',
      keys: 'mod+b',
      action: 'toggle-sidebar',
      enabled: true,
      preventDefault: true,
      allowInInputs: false,
    },
    {
      id: 'toggle-activity-bar',
      name: 'Toggle Activity Bar',
      description: 'Show or hide the activity bar',
      scope: 'global',
      category: 'application',
      keys: 'mod+j',
      action: 'toggle-activity-bar',
      enabled: true,
      preventDefault: true,
      allowInInputs: false,
    },
    {
      id: 'toggle-dual-pane',
      name: 'Toggle Dual Pane',
      description: 'Switch between single and dual pane editor mode',
      scope: 'global',
      category: 'application',
      keys: 'mod+d',
      action: 'toggle-dual-pane',
      enabled: true,
      preventDefault: true,
      allowInInputs: false,
    },
    {
      id: 'reload-note',
      name: 'Reload Note',
      description: 'Reload the current note',
      scope: 'global',
      category: 'application',
      keys: 'F5',
      action: 'reload-note',
      enabled: true,
      preventDefault: true,
      allowInInputs: false,
    },
    {
      id: 'toggle-line-wrapping',
      name: 'Toggle Line Wrapping',
      description: 'Enable or disable line wrapping in editor',
      scope: 'global',
      category: 'application',
      keys: 'alt+z',
      action: 'toggle-line-wrapping',
      enabled: true,
      preventDefault: true,
      allowInInputs: false,
    },
    {
      id: 'increase-font-size',
      name: 'Increase Font Size',
      description: 'Increase editor font size',
      scope: 'global',
      category: 'application',
      keys: 'mod+plus',
      action: 'increase-font-size',
      enabled: true,
      preventDefault: true,
      allowInInputs: false,
      platformOverrides: {
        windows: 'ctrl+plus',
        macos: 'cmd+plus',
        linux: 'ctrl+plus',
      },
    },
    {
      id: 'increase-font-size-equals',
      name: 'Increase Font Size (=)',
      description: 'Increase editor font size (= key)',
      scope: 'global',
      category: 'application',
      keys: 'mod+equal',
      action: 'increase-font-size',
      enabled: true,
      preventDefault: true,
      allowInInputs: false,
    },
    {
      id: 'decrease-font-size',
      name: 'Decrease Font Size',
      description: 'Decrease editor font size',
      scope: 'global',
      category: 'application',
      keys: 'mod+minus',
      action: 'decrease-font-size',
      enabled: true,
      preventDefault: true,
      allowInInputs: false,
    },

    // Editor Formatting Shortcuts
    {
      id: 'editor-bold',
      name: 'Bold',
      description: 'Apply bold formatting',
      scope: 'editor',
      category: 'formatting',
      context: 'editor',
      keys: 'mod+b',
      action: 'editor-bold',
      enabled: true,
      preventDefault: true,
      allowInInputs: true,
    },
    {
      id: 'editor-italic',
      name: 'Italic',
      description: 'Apply italic formatting',
      scope: 'editor',
      category: 'formatting',
      context: 'editor',
      keys: 'mod+i',
      action: 'editor-italic',
      enabled: true,
      preventDefault: true,
      allowInInputs: true,
    },
    {
      id: 'editor-code',
      name: 'Code',
      description: 'Apply inline code formatting',
      scope: 'editor',
      category: 'formatting',
      context: 'editor',
      keys: 'mod+`',
      action: 'editor-code',
      enabled: true,
      preventDefault: true,
      allowInInputs: true,
    },

    // Editor Heading Shortcuts
    {
      id: 'editor-heading-1',
      name: 'Heading 1',
      description: 'Apply heading 1 formatting',
      scope: 'editor',
      category: 'formatting',
      context: 'editor',
      keys: 'mod+shift+1',
      action: 'editor-heading-1',
      enabled: true,
      preventDefault: true,
      allowInInputs: true,
    },
    {
      id: 'editor-heading-2',
      name: 'Heading 2',
      description: 'Apply heading 2 formatting',
      scope: 'editor',
      category: 'formatting',
      context: 'editor',
      keys: 'mod+shift+2',
      action: 'editor-heading-2',
      enabled: true,
      preventDefault: true,
      allowInInputs: true,
    },
    {
      id: 'editor-heading-3',
      name: 'Heading 3',
      description: 'Apply heading 3 formatting',
      scope: 'editor',
      category: 'formatting',
      context: 'editor',
      keys: 'mod+shift+3',
      action: 'editor-heading-3',
      enabled: true,
      preventDefault: true,
      allowInInputs: true,
    },
    {
      id: 'editor-heading-4',
      name: 'Heading 4',
      description: 'Apply heading 4 formatting',
      scope: 'editor',
      category: 'formatting',
      context: 'editor',
      keys: 'mod+shift+4',
      action: 'editor-heading-4',
      enabled: true,
      preventDefault: true,
      allowInInputs: true,
    },
    {
      id: 'editor-heading-5',
      name: 'Heading 5',
      description: 'Apply heading 5 formatting',
      scope: 'editor',
      category: 'formatting',
      context: 'editor',
      keys: 'mod+shift+5',
      action: 'editor-heading-5',
      enabled: true,
      preventDefault: true,
      allowInInputs: true,
    },
    {
      id: 'editor-heading-6',
      name: 'Heading 6',
      description: 'Apply heading 6 formatting',
      scope: 'editor',
      category: 'formatting',
      context: 'editor',
      keys: 'mod+shift+6',
      action: 'editor-heading-6',
      enabled: true,
      preventDefault: true,
      allowInInputs: true,
    },
    {
      id: 'editor-paragraph',
      name: 'Paragraph',
      description: 'Convert to paragraph',
      scope: 'editor',
      category: 'formatting',
      context: 'editor',
      keys: 'mod+shift+0',
      action: 'editor-paragraph',
      enabled: true,
      preventDefault: true,
      allowInInputs: true,
    },

    // Editor List Shortcuts
    {
      id: 'editor-bullet-list',
      name: 'Bullet List',
      description: 'Create bullet list',
      scope: 'editor',
      category: 'formatting',
      context: 'editor',
      keys: 'mod+shift+8',
      action: 'editor-bullet-list',
      enabled: true,
      preventDefault: true,
      allowInInputs: true,
    },
    {
      id: 'editor-ordered-list',
      name: 'Ordered List',
      description: 'Create ordered list',
      scope: 'editor',
      category: 'formatting',
      context: 'editor',
      keys: 'mod+shift+7',
      action: 'editor-ordered-list',
      enabled: true,
      preventDefault: true,
      allowInInputs: true,
    },

    // Sequence Shortcuts (VSCode-style)
    {
      id: 'open-app-config',
      name: 'Open App Config',
      description: 'Open app configuration folder in file manager',
      scope: 'sequence',
      category: 'sequences',
      keys: ['mod+k', 'r'],
      action: 'open-app-config-folder',
      enabled: true,
      preventDefault: true,
      allowInInputs: false,
      timeout: 2000,
    },

    // Navigation Shortcuts (Future)
    {
      id: 'focus-editor',
      name: 'Focus Editor',
      description: 'Focus the main editor',
      scope: 'local',
      category: 'navigation',
      keys: 'mod+1',
      action: 'focus-editor',
      enabled: true,
      preventDefault: true,
      allowInInputs: false,
    },
    {
      id: 'focus-sidebar',
      name: 'Focus Sidebar',
      description: 'Focus the sidebar',
      scope: 'local',
      category: 'navigation',
      keys: 'mod+0',
      action: 'focus-sidebar',
      enabled: true,
      preventDefault: true,
      allowInInputs: false,
    },

    // Tree Navigation (Notes Tree specific)
    {
      id: 'tree-expand-all',
      name: 'Expand All',
      description: 'Expand all tree nodes',
      scope: 'local',
      category: 'navigation',
      context: 'notes-tree',
      keys: 'mod+shift+e',
      action: 'tree-expand-all',
      enabled: true,
      preventDefault: true,
      allowInInputs: false,
    },
    {
      id: 'tree-collapse-all',
      name: 'Collapse All',
      description: 'Collapse all tree nodes',
      scope: 'local',
      category: 'navigation',
      context: 'notes-tree',
      keys: 'mod+shift+c',
      action: 'tree-collapse-all',
      enabled: true,
      preventDefault: true,
      allowInInputs: false,
    },
  ];
}
